### ISSUE TITLE
Does,'t work with encrypted passowrds

### ISSUE THREAD

**Issue by schwitin** [sixro/confluence-maven-plugin#16]
Using encrypted passwords seems not to be working:

`
<server>
            <id>myconfluence</id>
            <username>aUsername</username>
            <password>{anEncryptedPassword}</password>
</server>
`

The above entry in the settins.xml results in:

Attempt to log in user 'aUsername' failed - incorrect username/password combination.

However plain text password works corrctly:

`
<server>
            <id>myconfluence</id>
            <username>aUsername</username>
            <password>aPasswod</password>
</server>
`

This [class](https://github.com/apache/maven-scm/blob/maven-scm-1.9.4/maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/AbstractScmMojo.java) may be an inpiration for dealing with encrypted passwords:

**Comment by sixro** [comment]
Thank you @schwitin for the hint
Tell me if you want to contribute on this change (or in the project)... I'll really appreciate that :+1:  :-)
