### ISSUE TITLE
Support Confluence REST-API

### ISSUE THREAD

**Issue by sakanaou** [sixro/confluence-maven-plugin#17]
Confluence deprecated the XML-RPC / SOAP-API since Confluence 5.5.
See https://developer.atlassian.com/confdev/confluence-rest-api/confluence-xml-rpc-and-soap-apis

Do you plan to switch to or support in parallel the REST-API instead?
https://developer.atlassian.com/confdev/confluence-rest-api

Thanks in advance!

**Comment by sixro** [comment]
Hi @sakanaou, I didn't know that... in order to "talk" with Confluence I'm using the library swizzle-confluence... I have to check whether they upgraded the library in order to talk using REST-API.
I'm going to check in the next days.
Thanks
  R

**Comment by sixro** [comment]
Hi @sakanaou, I found that swizzle-confluence did not upgrade their library to the newer implementation of Confluence(REST Api). Unfortunately, I do not have the time to change it 'cause I'll have to do it in my spare time (my current company does not use this plugin...).

If you think you can help me, you can open a pull request I will be glad to merge it  adding you to the contributor of this project as well. What do you think?
Thanks
  R

**Comment by sakanaou** [comment]
Hi @sixro. Unfortunately I cannot help you on that topic. We switched to the alternative "confluence-reporting-maven-plugin" as this plugin did better fit our needs. But they are also in the transition to the new API and use swizzle at the moment. I used your plugin with a Confluence 5.9, which works reliably. So until Confluence officially disables the XML-RPC-API the plugin is still usable.

**Comment by sixro** [comment]
oh perfect.
Thank you @sakanaou ! :)
  R
